version: "2"

services:
  auca-judge-front:
    volumes:
      - "./auca-judge-front:/auca-judge-front"

  auca-judge-queue:
    volumes:
      - "./auca-judge-queue:/auca-judge-queue"
      - "./auca-judge-back:/auca-judge-back"
      - "/var/run/docker.sock:/var/run/docker.sock"
